config/routes.rb
MyStore::Application.routes.draw do
  
  resources :items do
  	get :upvote, on: :member
  	get :expensive, on: :collection
  end 
  # делает наш контроллер RESTFUL'om

  get "admin/users_count" => "admin#users_count"

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	
	has_many 				:positions
	belongs_to 				:user
	has_many 				:items, through: :positions


end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to  :user
	belongs_to	:commentable, polymorphic: true
end

app/models/item.rb
class Item < ActiveRecord::Base
	# не обязательно для rails 4
	# attr_accessible :price, :real, :weight, :description, :name
	# вылидации для вводимых данных
	validates :price, numericality: { greater_than: 0, allow_nil: true }
	validates :name, presence: true
	# i.save! прерывает и вызывает exeption, если не валидно

	# belongs_to :category

	#after_initialize {} # Item.new, Item.first	
	#after_save 		 {} # Item.save, Item.create, Item.update_attr
	#after_create 	 {}
	#after_update 	 {}
	#after_destroy 	 {}

	has_many :positions
	has_many :carts, through: :positions
	has_many :comments, as: :commentable
	has_and_belongs_to_many :items, 
        class_name: "Item", 
        join_table: :items_orders, 
        foreign_key: :item_id, 
        association_foreign_key: :order_id
end

app/models/order.rb
class Order < ActiveRecord::Base
	
	belongs_to :user
	has_many :comments, as: :commentable
	has_and_belongs_to_many :items

	before_save do
		raise "no items in order!" if items.empty?
	end

	def calculate_total
		write_attribute :total, items.map(&:price).inject(:+)
	end

	
end

app/models/position.rb
class Position < ActiveRecord::Base

	belongs_to :item
	belongs_to :cart

end

app/models/user.rb
class User < ActiveRecord::Base

	# ассоциации
	has_one :cart
	has_many :orders
	has_many :comments

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :check_if_admin

	def users_count
		@users_count = User.count
		render layout: "admin"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private

	  def render_403
	  	render file: "public/403.html", status: 403
	  end

	  def render_404
	  	render file: "public/404.html", status: 404
	  end

	  def check_if_admin
		render_403 unless params[:admin]
	  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	
	# filters
	before_filter	:find_item, only: [:show, :edit, :update, :destroy, :upvote]
	#before_filter	:check_if_admin, only: [:edit, :update, :new, :create, :destroy]

	# CRUD actions

	# /items GET
	# объект activerecord relation
	def index
		@items = Item
		@items = @items.where("price >= ?", params[:price_from]) 		if params[:price_from]
		@items = @items.where("created_at >= ?", 1.day.ago) 			if params[:today]
		@items = @items.where("votes_count >= ?", params[:votes_from]) 	if params[:votes_from]
		@items = @items.order("votes_count DESC, price")
		# @items = @items.includes(:image)
	end

	def expensive
		@items = Item.where("price > 1000")
		render "index"
	end

	# /items/id GET
	def show
		# намеренный вызов ошибки raise "exeption test!"
		# полезный гем для того, чтобы видеть ошибки
		unless @item
			render text: "Page not found", status: 404
		end
	end
	# /items/new GET
	def new
		@item = Item.new
	end
	# /items/1/edit GET
	def edit
	end
	# /items POST
	def create
		@item = Item.create(item_params)
		if @item.errors.empty?
			redirect_to item_path(@item) # /items/:id
		else
			render "new"
		end
	end
	# /items/1 PUT method work around by rails
	def update
		@item.update_attributes(item_params)
		if @item.errors.empty?
			flash[:success] = "Item successfully updated!"
			redirect_to item_path(@item) # /items/:id
		else
			flash.now[:error] =  "You made mistakes in your form"
			render "edit"
		end
	end
	# /items/1 DELETE
	def destroy
		@item.destroy
		render json: { success: true}
		ItemsMailer.item_destroyed(@item).deliver
	end

	def upvote
		@item.increment!(:votes_count)
		redirect_to action: "index"
	end

	private
		
		def find_item
			@item = Item.where(id: params[:id]).first
			render_404 unless @item
		end

		def item_params
			params.require(:item).permit(:name, :price, :description, :weight)
			# если запрещать нечего: permit!
		end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def urls_to_images(s)
		s.gsub! /\s(https:\/\/.*?\.(png|JPG))(\s|\Z)/,
				'<p><img src="\1"/></p>'	
		s.html_safe		
	end

	def urls_to_links(s)
		s.gsub! /\s(https:\/\/.*?)(\s|\Z)/,
				'<a href="\1">\1</a>'	
		s.html_safe		
	end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
There are <%= @users_count %> users on the site

app/views/items/_form.html.haml
= f.input :price
= f.input :name, label: "Название"
= f.input :description
= f.input :weight


<!-- = hidde_field_tag :admin, params[:admin] -->

app/views/items/edit.html.haml
%h1 Edit item

= simple_form_for @item do |f|
	
	= render partial: "form", locals: {f: f}

	%p= f.submit "Изменить товар"

app/views/items/index.html.erb
<!-- если не писать равно, то значит 
мы не выводим содержимое этого руби кода
в браузер -->
<!-- method link_to название ссылки, путь,
	сгенерированный рельсой -->

<h1>Items</h1>

<% if @items.empty? %>
	<b>No items in store</b>
<% else %>
<table class="items">
	<tr>
		<th>item id</th>
		<th>Name</th>
		<th>Created_at</th>
		<th>Price</th>
		<th></th>
		<th></th>
	</tr>

	<% @items.each do |i| %>

		<tr data-item_id="<%= i.id %>">
			<td><%= i.id %></td>
			<td><%= link_to i.name, item_path(i) %></td>
			<td><%= i.created_at %></td>
			<td><%= i.price %> руб.</td>
			<td><span class="deleteAction"> Удалить </span></td>
			<td>Рейтинг: <%= i.votes_count %>, <%= link_to "+", upvote_item_path(i) %></td>
		</tr>

	<% end %>	

</table>
<% end %>

<%= render "shared/email" %>	

app/views/items/new.html.haml
%h1= t("h1.form")

= simple_form_for @item do |f|
	
	= render partial: "form", locals: {f: f}

	%p= f.submit "Создать товар"

app/views/items/show.html.haml
%h1= @item.name
%ul
	%li= "#{@item.price} руб."
	%li= urls_to_links(urls_to_images(@item.description))
	%li #{t("item.weight")}: #{@item.weight} кг.

= render partial: "shared/email"

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="adminPanel">
		Admin
	</div>
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<p style="color: red;"><%= flash[:error] %></p>
<p style="color: green;"><%= flash[:success] %></p>
<%= yield %>

</body>
</html>

app/views/shared/_email.html.erb
<div class="email">
	<p> Пример паршиала </p>
</div>